package globals_rmc

func NewMatchmakeExtension() ProtocolInfo {
	me := ProtocolInfo{}
	me.protocolName = "Matchmake Extension"
	me.methodTable = map[uint32]string{
		1:  "CloseParticipation",
		2:  "OpenParticipation",
		3:  "AutoMatchmake_Postpone",
		4:  "BrowseMatchmakeSession",
		5:  "BrowseMatchmakeSessionWithHostUrls",
		6:  "CreateMatchmakeSession",
		7:  "JoinMatchmakeSession",
		8:  "ModifyCurrentGameAttribute",
		9:  "UpdateNotificationData",
		10: "GetFriendNotificationData",
		11: "UpdateApplicationData",
		12: "UpdateMatchmakeSessionAttribute",
		13: "GetlstFriendNotificationData",
		14: "UpdateMatchmakeSession",
		15: "AutoMatchmakeWithSearchCriteria_Postpone",
		16: "GetPlayingSession",
		17: "CreateCommunity",
		18: "UpdateCommunity",
		19: "JoinCommunity",
		20: "FindCommunityByGatheringId",
		21: "FindOfficialCommunity",
		22: "FindCommunityByParticipant",
		23: "UpdatePrivacySetting",
		24: "GetMyBlackList",
		25: "AddToBlackList",
		26: "RemoveFromBlackList",
		27: "ClearMyBlackList",
		28: "ReportViolation",
		29: "IsViolationUser",
		30: "JoinMatchmakeSessionEx",
		31: "GetSimplePlayingSession",
		32: "GetSimpleCommunity",
		33: "AutoMatchmakeWithGatheringId_Postpone",
		34: "UpdateProgressScore",
		35: "DebugNotifyEvent",
		36: "GenerateMatchmakeSessionSystemPassword",
		37: "ClearMatchmakeSessionSystemPassword",
		38: "CreateMatchmakeSessionWithParam",
		39: "JoinMatchmakeSessionWithParam",
		40: "AutoMatchmakeWithParam_Postpone",
		41: "FindMatchmakeSessionByGatheringIdDetail",
		42: "BrowseMatchmakeSessionNoHolder",
		43: "BrowseMatchmakeSessionWithHostUrlsNoHolder",
		44: "UpdateMatchmakeSessionPart",
		45: "RequestMatchmaking",
		46: "WithdrawMatchmaking",
		47: "WithdrawMatchmakingAll",
		48: "FindmatchmakeSessionByGatheringId",
		49: "FindMatchmakeSessionBySingleGatheringId",
		50: "FindMatchmakeSessionByOwner",
		51: "FindMatchmakeSessionByParticipant",
		52: "BrowseMatchmakeSessionNoHolderNoResultRange",
		53: "BrowseMatchmakeSessionWithHostUrlsNoHolderNoResultRange",
		54: "FindCommunityByOwner",
	}

	return me
}
